feat: adds delete account functionality to template
flutter/news_toolkit pull request #1152
Opened 2024-03-20 17:45 UTC by elianortega

## Description

- delete account has become a requirement in most reviews by Apple, so it would be great if it's added by default to the template.

## Screenshots

<img src="https://github.com/elianortega/news_toolkit/assets/54898038/79ca15df-4007-46be-9a8b-5bcaff017d12" width="300"/>

<img src="https://github.com/elianortega/news_toolkit/assets/54898038/f4b4cbb9-9dff-4d03-9f8e-a4d222da2b9f" width="300"/>

## Type of Change

- [X] ✨ New feature (non-breaking change which adds functionality)
- [ ] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

2024-03-21 18:27 UTC, matiasleyba requested changes
Looks good! Just a few comments to review.

2024-03-21 20:25 UTC, elianortega commented on flutter_news_example/lib/app/bloc/app_bloc.dart
> +      await _userRepository.logOut();
Agree, I missed that.

2024-03-21 20:28 UTC, elianortega commented on flutter_news_example/lib/l10n/arb/app_en.arb
> +  "userProfileDeleteAccountButton": "Delete account",
I agree, I think that would be the best approach, but as the document is currently not in alphabetical order I just added the new entries at the end. For example second item is `authenticationFailure` and third `unexpectedFailure`. As of now I just organized the new entries in alphabetical order but maybe that could be a change for another PR?

2024-03-21 21:00 UTC, elianortega commented on flutter_news_example/pubspec.lock
> +  dart: ">=3.1.0 <4.0.0"
No reason, I just ran `flutter pub get` using flutter `3.13.9` attempting to match the `pubspec.lock` `"flutter: ">=3.13.0"`. 

But later on my intention is to send another PR updating the whole template to flutter 3.16.9.

2024-03-21 21:01 UTC, elianortega commented on flutter_news_example/lib/user_profile/widgets/user_profile_delete_account_dialog.dart
> +        child: ListBody(
To be completely honest, this was probably me hitting `tab` for a copilot suggestion 😄.

2024-03-22 12:18 UTC, matiasleyba commented on flutter_news_example/lib/l10n/arb/app_en.arb
> +  "userProfileDeleteAccountButton": "Delete account",
Agree 👍🏻 let's sort them in another PR.

2024-03-22 12:37 UTC, matiasleyba commented on flutter_news_example/pubspec.lock
> +  dart: ">=3.1.0 <4.0.0"
Great! 👌🏻 but for this PR I think it's better to keep the dependencies as they are, since we haven't changed or added new dependencies.

2024-03-22 16:42 UTC, matiasleyba requested changes
Just a comment to review before merge

2024-03-22 16:45 UTC, elianortega commented on flutter_news_example/pubspec.lock
> +  dart: ">=3.1.0 <4.0.0"
I agree, just made the change 🎉

2024-03-22 16:56 UTC, matiasleyba approved these changes
LGTM!

2024-03-22 17:24 UTC, matiasleyba submitted a review, later dismissed

2024-03-22 18:54 UTC, matiasleyba commented
@elianortega I'm not being able to merge the PR, would you mind checking your fork repo to fix the issues there to see if after fixing the issues there we can merge it here, thanks in advance!

2024-03-23 00:42 UTC, elianortega commented
@matiasleyba I just checked the PR on my repository and it is failing on the `api.yaml` workflow on the `coverage` job because of files that were not even modified on this PR. This is the [job](https://github.com/elianortega/news_toolkit/actions/runs/8398064755/job/23002389497?pr=1). 

I'll check it out but I'm a bit more inclined to solve that on another PR, what do you think?

2024-03-25 12:00 UTC, matiasleyba approved these changes

2024-03-25 12:02 UTC, matiasleyba commented
@elianortega I agree, let's solve them in another PR.

2024-03-25 12:02 UTC, merged